site_name: DriftPy
theme:
  name: readthedocs
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.snippets
  - meta
  - pymdownx.tabbed:
      alternate_style: true
repo_url: https://github.com/drift-labs/driftpy
repo_name: drift-labs/driftpy
site_url: https://drift-labs.github.io/driftpy/
plugins:
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          options:
            filters:
              - "!^_"
              - "^__init__$"
              - "!^T$"
              - "!^get_clearing_house_state_account_public_key_and_nonce$"
            show_root_heading: true
            show_root_full_path: false
            show_if_no_docstring: true
  - search
nav:
  - index.md
  - clearing_house.md
  - clearing_house_user.md
  - accounts.md
  - addresses.md
extra_css:
  - css/mkdocstrings.css
  - css/custom.css
