site_name: DriftPy
theme:
  name: material
  icon:
    logo: material/chart-line
  favicon: img/drift.png
  palette:
    - scheme: default
      primary: deep-purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.snippets
  - meta
  - pymdownx.tabbed:
      alternate_style: true
repo_url: https://github.com/drift-labs/driftpy
repo_name: drift-labs/driftpy
site_url: https://drift-labs.github.io/driftpy/
plugins:
  - mkdocstrings:
      handlers:
        python:
          selection:
            filters:
              - "!^_"  # exlude all members starting with _
              - "^__init__$"  # but always include __init__ modules and methods
              - "!^T$"
              - "!^get_clearing_house_state_account_public_key_and_nonce$"
          rendering:
            show_root_heading: true
            show_root_full_path: false
            show_if_no_docstring: true
  - search
nav:
  - index.md
  - api_reference.md
extra_css:
  - css/mkdocstrings.css
  - css/custom.css